#!/usr/bin/env sh

# reload scripting additions on startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Configures the position of the status bar
yabai -m config external_bar               all:40:0

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# window borders
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff8E83B8
yabai -m config normal_window_border_color   0xff51425C
yabai -m config insert_window_border_color   0xff8E83B8

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_shadow                float
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize


# applications to ignore
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Creative Cloud$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off

echo "yabai configuration loaded.."